CadastroUnico
samuelcamilocosta/orion-bootcamp-back-boilerplate-2024 pull request #3
Opened 2024-10-14 22:33 UTC by Pedrohsantosg

2024-10-14 22:36 UTC, Pedrohsantosg reviewed
@samuelcamilocosta @Zord0m

2024-10-15 14:45 UTC, samuelcamilocosta requested changes

2024-10-15 14:45 UTC, samuelcamilocosta commented on coverage/clover.xml
Não é bom commitar a pasta de coverage, adicione ela no .gitignore, pois se for necessário, a pessoa irá gerar ele, igual rodar install e build.
Ele dificulta a avaliação do PR, pois sobe muitos arquivos desnecessários, juntos ao código que deverá ser analisado

2024-10-15 14:45 UTC, samuelcamilocosta commented on .env
Esse arquivo .env e as environments daqui não se fazem necessárias, já que elas são declaradas diretamente no docker-compose

2024-10-15 14:45 UTC, samuelcamilocosta commented on .eslintignore
> +docker/volumes/ReforcaApi_MongoDB
essa pasta do docker/volumes deve estar armazenada no pc de cada um, não deve trazê-la para o projeto ou commita-la, ela contém as informações do volume e cadastros internos do seu local e pode acabar vazando informações que você não queira compartilhar com terceiros.

2024-10-15 14:45 UTC, samuelcamilocosta commented on nodemon.json
>  {
a sua configuração de lint pessoal, afetou o projeto, trouxe vários arquivos que estavam com 4 espaçamentos ou uma tab para 2 espaçamentos, acabou deixando o projeto com arquivos em que alguns estão com espaçamentos de 2 espaços e 4 espaços, vamos manter o padrão de 4 espaços para não ter confusões com isso posteriormente e facilitar a identificação quando o código for alterado.

2024-10-15 14:45 UTC, samuelcamilocosta commented on package.json
> +    "jest": "^29.7.0",
Nos packages instalados, você verá as nomenclaturas ^, ~, etc.
O ^ significa que quando rodar o install, ele puxará da versão estipulada até a última versão disponível.
ou seja, se tiver `"jest": "^29.7.0",`, ele poderá instalar do 29.7 até a última versão disponível. se no ano que vem lançarem o 30.0, ele instalaria ela. 

Isso traz alguns riscos para o projeto, pense que você precisa subir esse projeto ano que vem, quando deu o install, ele puxou a versão 30.0 e nessa versão, eles mudaram a forma de configuração do jest. O seu projeto não rodaria.  O Package-lock, mantém o histórico das versões das bibliotecas instaladas, porém é comum de se ter alguns problemas em instalações de bibliotecas e remover o package-lock e o node-modules e reinstalar as bibliotecas. Ou seja, isso colocaria em risco o seu projeto.

Para garantirmos que o projeto estará funcionando devidamente, independente de quando rodarmos, é importante nós fixarmos as bibliotecas, sem a utilização dos acrônimos de majors e minors ^, ~, pois assim garantimos a instalação da versão que desejamos em todos os ambientes e atualizamos elas quando for necessário.

Posteriormente, entraremos mais a fundo sobre as versões dos pacotes, manter a segurança deles.

Deixar um link que explica um pouco mais sobre o versionamento semantico
[](https://nodejs.reativa.dev/0024-npm-semantic-versioning/index)

Sendo assim, vamos fixar todas as versões das bibliotecas, para garantir que o projeto de vocês mantenham sempre funcionando. :1st_place_medal:

2024-10-15 14:45 UTC, samuelcamilocosta commented on package.json
> +    "mongoose": "^8.7.1",
Por que instalar o mongoose se o projeto já possui o ORM TypeORM?

2024-10-15 15:13 UTC, samuelcamilocosta requested changes

2024-10-15 15:13 UTC, samuelcamilocosta commented on package-lock.json
o package-lock.json é um arquivo que pode ser adicionado ao .gitignore também, após realizar o fixamento das versões

2024-10-15 15:13 UTC, samuelcamilocosta commented on src/config/database.ts
a alteração da estrutura do projeto e trocar o ORM de TypeORM para Mongoose não foi conversado pelo time

2024-10-15 15:13 UTC, samuelcamilocosta commented on src/config/database.ts
e essa é uma mudança grande da estrutura do projeto, essa alteração deveria ter sido discutida ao menos nas dailys

2024-10-15 15:13 UTC, samuelcamilocosta commented on src/config/database.ts
vamos conversar sobre hoje a tarde

2024-10-15 15:13 UTC, samuelcamilocosta commented on src/config/database.ts
> +// import { DataSource } from 'typeorm';
Não deixar o código comentado, se ele não for ser mais utilizado, remova-o.
O histórico de commits não deixará você perder o código que já foi uma vez utilizado.
Por isso não precisa se preocupar, se for necessário utilizar o código novamente, só acessar ele pelo histórico de alterações/commits

2024-10-15 15:13 UTC, samuelcamilocosta commented on src/controller/HomeController.ts
> +  async createUser(req: Request, res: Response) {
Em questões de organizações do projeto e código, é bastante importante criar o próprio UserController para manter os endpoints de usuário nele. Pois o projeto irá se expandir, ficaria totalmente desorganizado manter todo o código dos controllers aqui dentro do home controller

2024-10-15 15:13 UTC, samuelcamilocosta commented on src/controller/HomeController.ts
> +function isValidEmail(email: string): boolean {
faltou documentar com TSDoc a função isValidEmail

2024-10-15 15:13 UTC, samuelcamilocosta commented on src/controller/HomeController.ts
> +      console.log('Token JWT gerado:', token);
Remover todos os console.log do código, pois eles podem mostrar valores no terminal que não deveriam ser exibidos, podendo mostrando informações a pessoas que não deveriam ter acesso a esses dados.

2024-10-15 20:31 UTC, Zord0m commented
Alterações feitas. @samuelcamilocosta

2024-10-17 16:12 UTC, closed without merging

2024-10-17 16:12 UTC, samuelcamilocosta commented
commits dessa branch foram adicionados a login final